resnet18:
  backbone: "resnet18"
  num_classes: 1
  pretrained: True

resnet50:
  backbone: "resnet50"
  num_classes: 1
  pretrained: True

convnext_tiny:
  backbone: "convnext_tiny"
  num_classes: 1
  pretrained: True

convnext_base:
  backbone: "convnext_base"
  num_classes: 1
  pretrained: True

resnet18_mil:
  backbone: "resnet18"
  output_dim: 1

resnet50_mil:
  backbone: "resnet50"
  output_dim: 1

convnext_tiny_mil:
  backbone: "convnext_tiny"
  output_dim: 1

clinical: {}

clinical_logreg:
  solver: "lbfgs"
  max_iter: 20000

clinical_xgb:
  objective: "binary:logistic"
  eval_metric: "aucpr"
  tree_method: "hist"
  n_jobs: 1

clinical_dt: {}

clinical_rf:
  n_jobs: 1

clinical_svm:
  max_iter: 100000
  dual: "auto"

clinical_nb: {}

clinical_svm_rbf: {}